name: Create Tags

on:
  push:
    branches:
      - feat/**
      - dev
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version_bump
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          
          if [[ "$BRANCH" == "main" ]]; then
            echo "level=major" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "dev" ]]; then
            echo "level=minor" >> $GITHUB_ENV
          else
            echo "level=patch" >> $GITHUB_ENV
          fi

      - name: Create tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.level }}

      # 태그 생성 실패 시 Slack 알림
      - name: Notify Slack on Tag Creation Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ 태그 생성 실패",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}\n*Branch:* ${{ steps.branch_info.outputs.branch }}\n*Event Type:* ${{ github.event_name }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "워크플로우 확인",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK