name: Create Tag

on:
  push:
    branches:
      - feat/**
      - dev
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.0.0-main.0"
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Parse Version
        id: version
        run: |
          # 태그에서 'v' 제거
          clean_tag=$(echo "${{ env.latest_tag }}" | sed -E 's/^v//')

          # 버전과 브랜치, 카운트 분리 (vX.Y.Z-브랜치.N)
          version_part=$(echo "$clean_tag" | cut -d '-' -f1)  # vX.Y.Z
          branch_part=$(echo "$clean_tag" | cut -d '-' -f2 | cut -d '.' -f1)  # 브랜치명
          count_part=$(echo "$clean_tag" | cut -d '.' -f2)  # 브랜치 내 카운트

          # 기본값 설정 (최초 태그일 경우)
          if [[ -z "$version_part" ]]; then version_part="0.0.0"; fi
          if [[ -z "$branch_part" ]]; then branch_part="${GITHUB_REF#refs/heads/}"; fi
          if [[ -z "$count_part" ]]; then count_part=0; fi

          # 버전 숫자 분리
          IFS='.' read -r major minor patch <<< "$version_part"
          branch_name="${GITHUB_REF#refs/heads/}"

          echo "Current version: $major.$minor.$patch-$branch_part.$count_part"

          # 브랜치에 따라 버전 증가
          if [[ "$branch_name" == "main" ]]; then
            ((major++))
            minor=0
            patch=0
            count_part=0  # main에서 새로운 버전 시작 시 count 리셋
          elif [[ "$branch_name" == "dev" ]]; then
            ((minor++))
            patch=0
            count_part=0  # dev에서 새로운 버전 시작 시 count 리셋
          elif [[ "$branch_name" == feat/* ]]; then
            ((patch++))
            count_part=0  # feat에서 새로운 버전 시작 시 count 리셋
          fi

          # 브랜치에서의 count 증가
          ((count_part++))

          # 새로운 태그 생성
          new_tag="v$major.$minor.$patch-$branch_part.$count_part"
          echo "New version: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      # 태그 생성 실패 시 Slack 알림
      - name: Notify Slack on Tag Creation Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ 태그 생성 실패",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Event Type:* ${{ github.event_name }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "워크플로우 확인",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
