name: Create Tag

permissions:
  contents: write
  checks: write

on:
  push:
    branches:
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine bump type
        id: determine_bump
        run: |
          if [[ "${GITHUB_REF##*/}" == feat/* ]]; then
            echo "bump_type=patch" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == dev ]]; then
            echo "bump_type=minor" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == main ]]; then
            echo "bump_type=major" >> $GITHUB_ENV
          else
            echo "bump_type=patch" >> $GITHUB_ENV # Default to patch if no condition matches
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.bump_type }}