name: PR Merge Build and Notify

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # CodeQL 결과를 보안 이벤트로 업로드하기 위해 필요
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # CodeQL 분석을 위해 전체 히스토리 가져오기

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java  # 필요에 따라 javascript, python 등 추가 가능
          queries: security-and-quality  # 또는 security-and-quality

      - name: Build with Gradle
        run: ./gradlew build
        id: build
        continue-on-error: true  # 빌드 실패 시에도 워크플로우 계속 진행 (Slack 알림용)

      # 빌드 성공 시에만 CodeQL 분석 실행
      - name: Perform CodeQL Analysis
        if: steps.build.outcome == 'success'
        uses: github/codeql-action/analyze@v3
        id: codeql
        continue-on-error: true  # CodeQL 실패 시에도 워크플로우 계속 진행 (Slack 알림용)

      # CodeQL 보안 취약점 확인
      - name: Check for CodeQL Security Issues
        if: steps.build.outcome == 'success' && steps.codeql.outcome == 'success'
        id: check_security_issues
        run: |
          # GitHub API를 사용하여 코드 스캐닝 알림 확인
          ALERTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open")
          
          # 열린 알림 수 계산
          ALERT_COUNT=$(echo $ALERTS | jq length)
          
          echo "Security alert count: $ALERT_COUNT"
          echo "alert_count=$ALERT_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$ALERT_COUNT" -gt 0 ]; then
            echo "Security vulnerabilities found!"
          fi

      # 빌드 실패 시 Slack 알림
      - name: Notify Slack on Build Failure
        if: steps.build.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "PR Merge 후 빌드 실패 :x:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "PR Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": true
                    },
                    {
                      "title": "Merged By",
                      "value": "${{ github.event.pull_request.merged_by.login }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      # CodeQL 분석 실패 시 Slack 알림
      - name: Notify Slack on CodeQL Failure
        if: steps.build.outcome == 'success' && steps.codeql.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff9900", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "PR Merge 후 CodeQL 분석 실패 :warning:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "PR Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": true
                    },
                    {
                      "title": "Merged By",
                      "value": "${{ github.event.pull_request.merged_by.login }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      # 보안 취약점 발견 시 Slack 알림
      - name: Notify Slack on Security Vulnerabilities
        if: steps.check_security_issues.outputs.alert_count > 0
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff9900", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "PR Merge 후 CodeQL 분석에서 보안 취약점 발견 :warning:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "PR Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": true
                    },
                    {
                      "title": "Merged By",
                      "value": "${{ github.event.pull_request.merged_by.login }}",
                      "short": true
                    },
                    {
                      "title": "취약점 수",
                      "value": "${{ steps.check_security_issues.outputs.alert_count }}개",
                      "short": true
                    },
                    {
                      "title": "보안 취약점 확인",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/security/code-scanning|Security Dashboard에서 확인>",
                      "short": false
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK